kind: Service
apiVersion: v1
metadata:
  name: mini-link-user-service
  namespace: mini-link-namespace
  labels:
    app: mini-link-user-label
spec:
  selector:
    app: mini-link-user-label
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
